"""added Registration model

Revision ID: 292be29e2888
Revises: 88eaac8a8dfd
Create Date: 2024-04-09 13:05:59.413770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292be29e2888'
down_revision = '88eaac8a8dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('father_fname', sa.String(), nullable=True),
    sa.Column('father_lname', sa.String(), nullable=True),
    sa.Column('mother_fname', sa.String(), nullable=True),
    sa.Column('mother_lname', sa.String(), nullable=True),
    sa.Column('adress', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    # ### end Alembic commands ###
