"""added the registration model

Revision ID: c547cc1a5a78
Revises: fd025260834c
Create Date: 2024-04-07 21:18:06.501759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c547cc1a5a78'
down_revision = 'fd025260834c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('father_fname', sa.String(), nullable=True),
    sa.Column('father_lname', sa.String(), nullable=True),
    sa.Column('mother_fname', sa.String(), nullable=True),
    sa.Column('mother_lname', sa.String(), nullable=True),
    sa.Column('adress', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accountings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_accountings_student_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_accountings_student_id_users'), 'users', ['student_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('accountings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_accountings_student_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_accountings_student_id_users', 'users', ['student_id'], ['id'])

    op.drop_table('registrations')
    # ### end Alembic commands ###
